---
- name: Put an init script in place so we can run TeamCity like a standard service
  template:
    src=teamcity.sh.j2
    dest=/etc/init.d/teamcity
    owner=root
    group=root
    mode=0755

- name: Ensure TeamCity is told to start at boot.
  service:
    name=teamcity
    enabled=yes

#- name: Now that our preparation work is done, start TeamCity
#  debug: msg="Notifying TeamCity to start."
#  notify:
#   - start teamcity

- name: start teamcity
  service:
    name: teamcity
    state: started
  register: teamcity_start
  failed_when: "'already running' not in teamcity_start.msg"

# The fun thing about TeamCity is that it really only starts when it gets its first request.
# Fire and forget a curl req to get TeamCity working
- name: Fire off a request to the listening TeamCity port to fire up the service
  command: curl --max-time 30 --fail --silent localhost:{{teamcity_port}}
  async: 35
  poll: 0

- name: Unblock the teamcity serving port from UFW
  ufw: state=enabled
  ufw: rule=allow port={{teamcity_port}} proto=tcp
