---
# file: api_nginx_nodejs/deaults/main.yml
api_dest_folder: "/srv/api"
api_git_repo: "https://github.com/augmate/api.git"

user: api_user

http_port: 80
https_port: 443


#base nginx setup

nginx_user: www-data
nginx_group: www-data
nginx_pid: /var/run/nginx.pid

nginx_root: /srv/api/
nginx_worker_processes: "{{ansible_processor_count}}"
nginx_worker_connections: 768
nginx_keepalive_timeout: 65
nginx_log_file_access: /var/log/nginx/access.log
nginx_log_file_error: /var/log/nginx/error.log

#----#

#api specific variables
api_user: api_user
api_node_port: 3000

#http://nginx.org/en/docs/http/server_names.html
api_nginx_server_name: api.augmate.*
api_nginx_root: /srv/api
api_nginx_log_file_access: /var/log/nginx/api_access.log
api_nginx_log_file_error: /var/log/nginx/api_error.log