---
# file: api_nginx_nodejs/deaults/main.yml
api_dest_folder: "/srv/api"
api_git_repo: "https://github.com/augmate/api.git"

nginx_user: www-data
nginx_group: www-data

user: www-data
#user: {{ nginx_user }}

#http://nginx.org/en/docs/http/server_names.html
nginx_server_name: api.augmate.*
nginx_root: /srv/api/


http_port: 80
https_port: 443

worker_processes: "{{ ansible_processor_count }}"
pid: /var/run/nginx.pid
worker_connections: 768

log_file_access: /var/log/nginx/api.log
node_port: 3000