---
#file: nodejs/tasks/main.yml


#- #name: "Install packages nodejs and npm"
  #apt: 
  #  pkg={{ item }} state=present
  #  state=present
  #with_items:
    #- nodejs
    #- npm


#
# Check if the version we pulled from aptitude is what we wanted.
# No? Try to specify the package by version for aptitude.
# Still not good? Pull and make from source.
#

####################################################################################################
# nodejs 

- name: "Check installed version of nodejs"
  shell: /usr/bin/test "$({{nodejs_path}}/bin/nodejs --version 2> /dev/null)" = "v{{version_nodejs}}"
  register: nodejs_version_installed
  ignore_errors: True
  changed_when: nodejs_version_installed.rc == 1

- name: "try to install nodejs={{version_nodejs}} from aptitude if the version check failed"
  apt: pkg="nodejs={{version_nodejs}}" state=present
  ignore_errors: True
  register: aptitude_specific_version_install
  when: nodejs_version_installed.changed

- name: "Test if nodejs happens to be in place anyway..."
  command: /usr/bin/test "$({{nodejs_path}}/bin/nodejs --version 2> /dev/null)" = "v{{version_nodejs}}"
  ignore_errors: True
  register: node_installed_test

- name: "Print the debug output from failing to install a specific version of nodejs"
  debug: msg="{{ aptitude_specific_version_install }}"
  when: (aptitude_specific_version_install is defined and aptitude_specific_version_install.failed) or node_installed_test.rc == 1

- name: "Download nodejs from source"
  get_url: url={{nodejs_tarball_url}} dest={{nodejs_tmp_dir}}/{{nodejs_tar_filename}}
  when: (aptitude_specific_version_install is defined and aptitude_specific_version_install.failed) or node_installed_test.rc == 1

- name: "Verify SHASUM of nodejs {{version_nodejs}}"
  shell: curl {{nodejs_shasum_url}} | grep {{nodejs_tar_filename}} | sha1sum -c chdir={{nodejs_tmp_dir}}
  when: (aptitude_specific_version_install is defined and aptitude_specific_version_install.failed) or node_installed_test.rc == 1

- name: "Unpack nodejs tar"
  shell: tar -xvzf {{nodejs_tar_filename}} chdir={{nodejs_tmp_dir}}  
  when: (aptitude_specific_version_install is defined and aptitude_specific_version_install.failed) or node_installed_test.rc == 1

- name: "Compile and install nodejs {{ nodejs_version_tag }}"
  shell: ./configure --prefix={{nodejs_path}} && make && make install chdir={{nodejs_tmp_dir}}{{nodejs_file_tag}}
  sudo: true
  when: (aptitude_specific_version_install is defined and aptitude_specific_version_install.failed) or node_installed_test.rc == 1

- debug: msg={{node_installed_test.rc}}==1
