---
# file: api_nginx_nodejs/tasks/nodejs.yml

- name: make the serving directory exists
  file:
    state=directory
    path={{api_nginx_root}}
    owner={{nginx_user}}
    group={{nginx_group}}
    mode=0775

# Force a shallow-depth clone of the repo as our api user.
# hostkey should already be populated safely this role's main.yml
# If you're okay with stranger-danger, add accept_hostkey=yes
- name: git clone the repo into our serving directory
  git:
    repo=git@github.com:augmate/api.git
    depth=1
    dest={{api_nginx_root}}
    version=master
    force=yes
  sudo: yes
  sudo_user: "{{api_user}}"

- name: install our required node modules [ present, and *latest* version ]
  npm:
    name: "{{item}}"
    state: latest
    global: yes
  with_items:
    - pm2

- name: Make sure we have an /etc/ssl dir to put our cert and key into for mongodb
  file:
    state=directory
    path=/etc/ssl/
    owner=root
    group=root
    mode=0755

- name: Put our mongodb cert in place
  copy:
    src=keys/id_rsa_deploy_key.pub
    dest=/etc/ssl/mongodb.cert
    owner={{user}}
    group={{user}}
    mode=0640

- include_vars: mongodb_key.yml

- name: Put our mongodb (encrypted) key in place
  copy:
    content="{{mongodb_key}}"
    dest=/etc/ssl/mongodb.key
    owner={{user}}
    group={{user}}
    mode=0640

#- name: check that our required node modules [ only present, no constraint on version ]
#  npm:
#    name: "{{item}}"
#    state: present
#    global: yes
#  with_items:
#    -
