---
# file: api_nginx_nodejs/tasks/nodejs.yml

- name: make the serving directory exists
  file:
    state=directory
    path={{api_nginx_root}}
    owner={{nginx_user}}
    group={{nginx_group}}
    mode=0775

# Force a shallow-depth clone of the repo as our api user.
# hostkey should already be populated safely this role's main.yml
# If you're okay with stranger-danger, add accept_hostkey=yes
- name: git clone the repo into our serving directory
  git:
    repo=git@github.com:augmate/api.git
    depth=1
    dest={{api_nginx_root}}
    version=master
    force=yes
  sudo: yes
  sudo_user: "{{api_user}}"

- name: install our required node modules
  npm:
    name: "{{item}}"
    state: latest
    global: yes
  with_items:
    - pm2



