---

teamcity_download_url: http://download.jetbrains.com/teamcity/TeamCity-8.1.3.tar.gz
teamcity_download_sha256: 336c8378f4083e415040a52ef7019d06ec72a32f50e6c7804902718217d2ef66

teamcity_download_directory: /var/cache
teamcity_download_file: "{{teamcity_download_directory}}/teamcity.tar.gz"
teamcity_install_directory: /srv/teamcity

#TODO: hook onto output of unpack if we can to detect the install dir name

teamcity_directory: "{{teamcity_install_directory}}/TeamCity"
teamcity_bin_directory: "{{teamcity_directory}}/bin"
teamcity_agent_bin_directory: "{{teamcity_directory}}/buildAgent/bin"

TEAMCITY_DATA_PATH: '/var/teamcity'

teamcity_install_conf_directory: "{{teamcity_directory}}/conf"
teamcity_buildagent_conf_directory: "{{teamcity_directory}}/buildAgent/conf"
teamcity_conf_directory: "{{TEAMCITY_DATA_PATH}}/config"

teamcity_port: 8111
teamcity_buildagent_port: 9090

teamcity_purpose: agent

#todo: jinja multiplication here could help.
percent_total: "{{ansible_memtotal_mb * .8 }}"

#do not set the maxperm size beyond the available box ram.
teamcity_max_mem: "{% if ansible_memtotal_mb >= 300 %}270{% else %}125{% endif %}"

TEAMCITY_SERVER_MEM_OPTS: "-XX:MaxPermSize={{teamcity_max_mem}}m"
# else set to 80% of ansible_memtotal_mb
#TEAMCITY_SERVER_MEM_OPTS: '-XX:MaxPermSize=270m'
#TEAMCITY_SERVER_OPTS: ""

java_jbdc_postgres_driver: postgresql-9.3-1101.jdbc41.jar
java_jbdc_postgres_driver_url: "http://jdbc.postgresql.org/download/{{java_jbdc_postgres_driver}}"

java_jbdc_postgres_driver_download_directory: /var/cache
java_jbdc_postgres_driver_download_file: "/var/cache/{{java_jbdc_postgres_driver}}"

java_jbdc_postgres_driver_install_directory: "{{TEAMCITY_DATA_PATH}}/lib/jdbc/"
java_jbdc_postgres_driver_dest: "{{java_jbdc_postgres_driver_install_directory}}/{{java_jbdc_postgres_driver}}"
