---
# file: playbooks/buildbox.yml
- name: Teamcity Master Servers
  hosts: buildserver-master
  sudo: True
  vars_files:
    - roles/teamcity/vars/teamcity_postgres_password.yml
  roles:
    - { role: postgresql }
    - { role: java }
    - { role: teamcity, teamcity_purpose: master}
  tags:
  - master
  tasks:
    - debug: msg="Teamcity Master tasks..."

    - name: add a teamcity database if it doesn't already exist
      postgresql_db:
        name=teamcity
        login_user='postgres'
        encoding='UTF-8'
        state=present
      sudo: yes
      sudo_user: postgres

    #http://docs.ansible.com/postgresql_user_module.html
    - name: add a postgres user 'teamcity' with 'all' privileges on teamcity's database
      postgresql_user:
        db=teamcity
        name=teamcity
        priv=ALL
        password="{{teamcity_postgres_password}}"
        state=present
      sudo: yes
      sudo_user: postgres

    - name: Now that our preparation work is done, start TeamCity
      service: name=teamcity state=started
      register: teamcity_start
      failed_when: "'already running' not in teamcity_start.msg"

  handlers:
    - include: roles/teamcity/handlers/main.yml


- name: Teamcity Build Agents
  hosts: buildserver-agent
  sudo: True
  roles:
    - { role: java }
    - { role: teamcity }
  tags:
  - agent
  tasks:
    - debug: msg="Teamcity Agent tasks..."
