---
#file playbooks/step_two.yml
- hosts: all
  sudo: True

  vars_files:
    - ../group_vars/all

  tasks:
    #users and groups
    - name: add system groups 
      group: name=cron gid=1001 state=present

    - name: add developers group
      group: name=developers gid=1002 state=present 

    - name: add system users
      user: name=cron state=present system=yes createhome=no uid=1001 state=present

    - name: add human users 
      user: 
        name="{{ item.username }}"
        comment="{{ item.comment }}"
        uid="{{ item.uid }}"
        groups="{{ item.groups }}"
        shell="/bin/bash"
        createhome=yes
        state=present
      with_items: human_users

    # add user ssh keys
    - authorized_key:
        user="{{ item.username }}"
        key="{{ item.ssh_public_key }}"
      with_items: human_users

    #core services and iptables 
    - name: "install ufw to manage iptables, ntp for time synchronization, fail2ban to block brute force attempts"
      action: apt pkg={{ item }} state=present
      with_items:
        - ufw #should already be installed
        - ntp 
        - fail2ban

    #Now that we're done, get rid of our provisioning user (keep the group).
    - action: user name=admin state=absent

    - set_fact: 
        step_two: 'OK'